name: UI tests

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    run-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                playwright install --with-deps

            - name: Run Playwright tests with pytest and generate Allure results
              run: |
                pytest -m regression --alluredir=allure_results --numprocesses 2

            - name: Upload Allure Report
              uses: actions/upload-artifact@v4
              with:
                name: uploaded_report
                path: |
                    allure_results





    publish-report:
        name: Publish Allure report
        needs: run-tests
        runs-on: ubuntu-latest

        steps:
            - name: Download report
              if: always()
              uses: actions/download-artifact@v4
              with:
                name: uploaded_report

            - name:  Get Allure history
              uses: actions/checkout@v4
              if: always()
              continue-on-error: true
              with:
                ref: gh-pages
                path: gh-pages

            - name: Generates Allure Report with history
              uses: simple-elf/allure-report-action@v1.7
              if: always()
              with:
                allure_results: allure_results
                allure_history: allure_history

            - name: Deploy report to Github Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: gh-pages
                publish_dir: allure_history
